version: "3.9"
   
services:
  db:
    image: postgres
    container_name: sample_db
    volumes:
      - sample_dev_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  django:
    build:
      context: ./backend
      dockerfile: ./docker/django/Dockerfile
      target: dev
    container_name: sample_django
    volumes:
      - ./backend/src:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./backend/.envs/.global
    command: /start

  react:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
      target: dev
    container_name: sample_react
    volumes:
      - ./frontend:/web
      - /web/node_modules
    ports:
      - 3000:3000
    depends_on:
      - django
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    command: npm start

volumes:
  sample_dev_vol: {}