# Generated by Django 3.1.10 on 2022-05-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='created', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='updated', verbose_name='updated')),
                ('archived', models.BooleanField(default=False, help_text='archived', verbose_name='archived')),
                ('url', models.URLField(help_text='url', verbose_name='url')),
                ('short_url', models.CharField(help_text='short_url', max_length=15, verbose_name='short_url')),
            ],
            options={
                'verbose_name': 'url_short',
                'verbose_name_plural': 'url_shorts',
                'db_table': 'url_short.url_shorts',
            },
        ),
    ]
