#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "$RUN_ENVIRONMENT" = "development" ]
then
    python manage.py migrate
    python manage.py runserver 0.0.0.0:8000
fi

if [ "$RUN_ENVIRONMENT" = "production" ]
then
    python manage.py migrate
    python manage.py collectstatic --noinput

    gunicorn core.wsgi:application --bind 0.0.0.0:8000
fi
